site_name: Blueswen

repo_url: https://github.com/blueswen/blueswen.github.io
repo_name: blueswen/blueswen.github.io
site_url: https://blueswen.github.io/
edit_uri: ""

extra_css:
  - stylesheets/main.css

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: octicons/copilot-96
  
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  
  palette:
    primary: white

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - meta
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - glightbox
  - social:
      cards_layout_options:
        background_color: "#0085A1" 
        color: "#FFFFFF"
        font_family: Noto Sans TC
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      fallback_to_build_date: true
  - meta
  - tags
  - blog-extension:
      categories_toc: true
      post_readtime: false
      pagination_per_page: 10
      pagination_keep_content: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - group:
      plugins:
        - optimize
        - minify
nav:
  - Home: index.md
  - Portfolio: portfolio.md
  - Talks: talks.md
  - Publications: publications.md
  - Blog:
     - blog/index.md
  - Tags: tags.md
